#!/usr/bin/env bash

#ddev-generated
## Description: Run pnpm in the web container
## Usage: pnpm [flags] [args]
## Example: "ddev pnpm"
## ExecRaw: true
## HostWorkingDir: true
## MutagenSync: true

if [ "$(pnpm config get store-dir --global)" == "undefined" ]; then
  pnpm config set store-dir "$PNPM_HOME" --global
fi

# If a $PNPM_DIRECTORY is set, run our PNPM commands in that directory
if [ -n "$PNPM_DIRECTORY" ]; then
  pnpm --dir "$PNPM_DIRECTORY" "$@"
else
  pnpm "$@"
fi
